Traceback (most recent call last):
  File "/usr/share/miniconda/envs/ols-stats/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/ols-stats/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/ols-stats/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/ols-stats/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/ols-stats/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/ols-stats/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/ols-stats/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
path = geopandas.datasets.get_path('naturalearth_lowres')
world_df = geopandas.read_file(path)

country_continent_fp = Path("../data/country_alpha_2_continent.csv")
country_continent_df = (
    pd.read_csv(country_continent_fp, index_col=0)
)
COUNTRY_ALPHA2_TO_CONTINENT = country_continent_df.to_dict()['Continent']

def get_continent(country):
    """
    Get continent

    :param country: name of the country
    """
    py_country = pycountry.countries.get(name=country)
    if py_country is None:
        py_country = pycountry.countries.get(common_name=country)
    if py_country is None:
        return ""
    else:
        if py_country.alpha_2 not in COUNTRY_ALPHA2_TO_CONTINENT:
            return ""
        else:
            return COUNTRY_ALPHA2_TO_CONTINENT[py_country.alpha_2]


def get_country_3(country):
    """
    Get country code

    :param country: name of the country
    """
    py_country = pycountry.countries.get(name=country)
    if py_country is None:
        py_country = pycountry.countries.get(common_name=country)
    if py_country is None:
        return ""
    else:
        return py_country.alpha_3


rate = {
    "GBP": 1,
    "USD": 0.8,
    "EUR": 0.86,
    "INR": 0.0095,
    "XAF": 0.0013,
    "ZAR": 0.042,
    "ARS": 0.0022,
    "": 1
}
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m path [38;5;241m=[39m [43mgeopandas[49m[38;5;241;43m.[39;49m[43mdatasets[49m[38;5;241;43m.[39;49m[43mget_path[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mnaturalearth_lowres[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m world_df [38;5;241m=[39m geopandas[38;5;241m.[39mread_file(path)
[1;32m      4[0m country_continent_fp [38;5;241m=[39m Path([38;5;124m"[39m[38;5;124m../data/country_alpha_2_continent.csv[39m[38;5;124m"[39m)

File [0;32m/usr/share/miniconda/envs/ols-stats/lib/python3.12/site-packages/geopandas/datasets/__init__.py:18[0m, in [0;36mget_path[0;34m(dataset)[0m
[1;32m     12[0m error_msg [38;5;241m=[39m (
[1;32m     13[0m     [38;5;124m"[39m[38;5;124mThe geopandas.dataset has been deprecated and was removed in GeoPandas [39m[38;5;124m"[39m
[1;32m     14[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124m1.0. You can get the original [39m[38;5;124m'[39m[38;5;132;01m{[39;00mdataset[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m data from [39m[38;5;124m"[39m
[1;32m     15[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mne_message[38;5;250m [39m[38;5;28;01mif[39;00m[38;5;250m [39m[38;5;124m'[39m[38;5;124mnatural[39m[38;5;124m'[39m[38;5;250m [39m[38;5;129;01min[39;00m[38;5;250m [39mdataset[38;5;250m [39m[38;5;28;01melse[39;00m[38;5;250m [39mnybb_message[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     16[0m )
[1;32m     17[0m [38;5;28;01mif[39;00m dataset [38;5;129;01min[39;00m _prev_available:
[0;32m---> 18[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(error_msg)
[1;32m     19[0m [38;5;28;01melse[39;00m:
[1;32m     20[0m     error_msg [38;5;241m=[39m (
[1;32m     21[0m         [38;5;124m"[39m[38;5;124mThe geopandas.dataset has been deprecated and [39m[38;5;124m"[39m
[1;32m     22[0m         [38;5;124m"[39m[38;5;124mwas removed in GeoPandas 1.0. New sample datasets are now available [39m[38;5;124m"[39m
[1;32m     23[0m         [38;5;124m"[39m[38;5;124min the geodatasets package (https://geodatasets.readthedocs.io/en/latest/)[39m[38;5;124m"[39m
[1;32m     24[0m     )

[0;31mAttributeError[0m: The geopandas.dataset has been deprecated and was removed in GeoPandas 1.0. You can get the original 'naturalearth_lowres' data from https://www.naturalearthdata.com/downloads/110m-cultural-vectors/.

